### PR TITLE
BNGP-4891: Change to metric explanation

### PR DESCRIPTION
**Pull request by thousand-leaves**
https://eaflood.atlassian.net/browse/BNGP-4891

This change amends the metric explanation content on the credits journey.

### CODE REVIEW

**Comment by Stewart-Jumbe** [comment]
Thanks for the work:-), I noticed the following differences between the preview page provided by Dan and what you added to the upload-metric-file page:

- add 'opens in new tab' text
- remove hyperlink to GOV.UK text
- increase font size of title ('Upload the statutory biodiversity metric')

bullet point updates:
- add 'an' in front of "XLSM or XLSX"
- add no in front of "larger than 50MB"
 
prototype sample

**Comment by thousand-leaves** [comment]
- add 'opens in new tab' text - **ADDED**
- remove hyperlink to GOV.UK text - can assume this should be a hyperlink as have been provided with the 2nd link for GOV.UK?
- increase font size of title ('Upload the statutory biodiversity metric') - font style is global
- add 'an' in front of "XLSM or XLSX" - **ADDED**
- add no in front of "larger than 50MB" - **ADDED**

**Review by Stewart-Jumbe — DISMISSED** [review]
Great work :-)

**Review by KiranVarma02 — APPROVED** [review]

**Comment by shaundefra** [comment]
tested locally

**Pull request merged**
