### PR TITLE
BNGP-5373: check allocation metric has at least one match

### PR DESCRIPTION
**Pull request by paulsimonandrews**

### CODE REVIEW

**Review by StuAA78 — APPROVED** [review]
👍

**Comment by thousand-leaves** [comment]
Error message at top of page needs to link to error message at the bottom (and be red).

Also to test i edited the dev metric so that there are no matches. Do we want to include this in the test files?
[CC-DEV-BNGREG-M7T5N-BQ3Z4_Metric-No-Matches.xlsx](https://github.com/user-attachments/files/16976471/CC-DEV-BNGREG-M7T5N-BQ3Z4_Metric-No-Matches.xlsx)

No matches metric error message

**Comment by paulsimonandrews** [comment]
> Error message at top of page needs to link to error message at the bottom (and be red).

Fixed.
 
> Also to test i edited the dev metric so that there are no matches. Do we want to include this in the test files? [CC-DEV-BNGREG-M7T5N-BQ3Z4_Metric-No-Matches.xlsx](https://github.com/user-attachments/files/16976471/CC-DEV-BNGREG-M7T5N-BQ3Z4_Metric-No-Matches.xlsx)

I think for the moment the unit tests should be fine here with the mocked habitat data

**Review by thousand-leaves — APPROVED** [review]

**Comment by shaundefra** [comment]
tested locally

**Pull request merged**
