### PR TITLE
BNGP-5193: Upgrade GOV UK Design System to v5

### PR DESCRIPTION
**Pull request by StuAA78**
https://eaflood.atlassian.net/browse/BNGP-5193

This PR covers breaking and recommended changes as documented in the [changelog](https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md). Amending task lists to use the new `govukTaskList` component is covered in https://github.com/DEFRA/biodiversity-net-gain-service/pull/813

Changes:
- Update dependencies
- Update paths as required by new version
- Update `Beta` phase banner to correct capitalisation as per v5 style
- Update CSP hash
- Remove deprecated classes, attributes, tags
- Remove IE8 support features (no longer supported in v5)
- Update new crown logo as required

### CODE REVIEW

**Review by Stewart-Jumbe — DISMISSED** [review]
Great work

**Review by thousand-leaves — COMMENTED** [review]
tested locally and works as expected

**Review by thousand-leaves — DISMISSED** [review]

**Comment by shaundefra** [comment]
closing this branch as duplicated within https://github.com/DEFRA/biodiversity-net-gain-service/pull/813

**Review by thousand-leaves — APPROVED** [review]

**Comment by shaundefra** [comment]
tested locally

**Pull request merged**
