### PR TITLE
Fix metric upload bug

### PR DESCRIPTION
**Pull request by teddmason**
As part of testing AV scanning there is a bug where by if a metric successfully gets AV scanned and returned then the app is throwing a "blob not found error" and this is due to the assumption that the function message will have the containerName set, however when the message comes from AV scanning service bus this is not the case. So fix is to set the containerName manually.

### CODE REVIEW

**Review by paulsimonandrews — APPROVED** [review]
LGTM

**Review by pwadmore-ea — APPROVED** [review]
The upload of a non-Biodiversity Metric spreadsheet uses generic file upload error handling rather than user friendly context sensitive error handling.

A follow on story to provide user friendly context sensitive error handling is suggested.

**Comment by teddmason** [comment]
Closing this off as have recreated the branch based on master as running rebase was a nightmare.  Created a branch from master then merged in this branch and stripped out any debug/testing code not needed in prod.

**Comment by teddmason** [comment]
New pr https://github.com/DEFRA/biodiversity-net-gain-service/pull/370

**Pull request closed without merging**
