### PR TITLE
Defra ID mocking and database bug fixes

### PR DESCRIPTION
**Pull request by teddmason**

### CODE REVIEW

**Comment by teddmason** [comment]
This is awaiting https://github.com/DEFRA/biodiversity-net-gain-service/pull/449 to be merged to master.  Once done this pr needs its base branch changing to master. And needs cleaning up.

The key parts of this pr are:
- Defra ID mocking
- Database pool init fix

**Review by paulsimonandrews — COMMENTED** [review]
LGTM

**Review by paulsimonandrews — COMMENTED** [review]
LGTM

**Review by paulsimonandrews — APPROVED** [review]
LGTM

**Pull request merged**
