### PR TITLE
Feature/BNGP-3450: Metric Upload - add I do not have a metric file option

### PR DESCRIPTION
**Pull request by usman-j-shaikh**

### CODE REVIEW

**Review by teddmason — CHANGES_REQUESTED** [review]
@usman-j-shaikh this ticket is only meant to be for the developer journey. But the work has merged together the landowner and the developer versions of this page. The content on the pages should be different.  This work should only be for the developer journey. Please can you rectify.

**Review by AjinkyaJawalkar — APPROVED** [review]
Code looks good to me. Functionality needs to be checked And please resolve the conflict

**Review by AjinkyaJawalkar — CHANGES_REQUESTED** [review]
Resolve conflict

**Review by AjinkyaJawalkar — APPROVED** [review]
PR looks good to me.

**Review by teddmason — APPROVED** [review]

**Pull request merged**
