### PR TITLE
BNPG-4289: Footer - cookie statement shouldn't need to be authenticated modified route of cookies

### PR DESCRIPTION
**Pull request by usman-j-shaikh**

### CODE REVIEW

**Review by AjinkyaJawalkar — APPROVED** [review]

**Review by soorajvdefra — DISMISSED** [review]
Changes are looks fine

**Review by AjinkyaJawalkar — APPROVED** [review]
PR looks good to me

**Review by soorajvdefra — COMMENTED** [review]
changes are looks ok

**Comment by LeenaKu** [comment]
Tested and passed. 
@shaundefra Can you merge this please ?

**Pull request merged**
